apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-7dpm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-service-tenant/appstudio/dc-metro-map-7dpm@sha256:9153524c01a5cb4837a419082494a0a6003880723199af13f38de9f247c89c53
        name: my-nodejs
        resources: {}
status: {}
